gateway:
  ip: 172.18.0.5

openapi:
  certkeyNo: '{cipher}AQBQgE3wvpfO27l5/LnLLgN0dArIZOHDVSiDZoTgBVek15NKgkunXQ5TDlT4C6mXhQKjuyFjD5CcK2qRTjHlfVc80zWlgCGhaaGem5s3J8ZeT8QY7mnUO2b4SRleFv2ph5TwGuBCnTnBJ67LUy9ZLoq9FPeGN77tBQl2VCkE6kiANz+Zirl4sBu96YVIPa6Q7pXTB/eRf5qQQcSRmu01GStYOOMuz4yQ28X4nEFjjx+V2vCNfVwNDjheC9NcwENi4b6NSYdh02yXwz1FXKzFwgvDsfaQb41qmQPyn7jYdmXRnuEg6fFTe/pshFdlSTeWHFY19m2fcWiA67x4N6GLTYog3Szt7wK5+JsqogdDChob0nCqir0zQJe9pmGBSyq2hBw='
  key: '{cipher}AQBHFlHT4pRw2YMBPciEjgnxyLtFJ8WlFzzeTWrYX5zqmyunp5W2WcCsklAV48R3feO20RZ4k78g59hIXKk2ri3lcYTpO6gjwQ/mdJUBcvMcS/qE/wOOOSqBCbBIUCf2aSFB4kdVp0xZhKMskU7rNrZ1Du6Lt0+GxV/nbDOsrdADPgbfXv3NYfxfZkoE/zrUuPP2AHrljQickhzi/DQ8xxKTaFSVT1Ain4UizOsSb+lyqeLiDVO7klRAsaUmW8nP3RwtiySCwbu3Xqym2UBtjvGRKkoIAP1rdEH1tdrhDEaZhxQpHFyEMtMsun0RL607gCNMjny2OX/ez4ooQIXaf8tHEH8G4/MgSgqqOjA44hMyjviAhIyOOZ3qMqk/muEX32ugF9sSquOcyvuH9vh+tAG2eoqCJbQl1fkpZrRPqVV46A=='
  typeSearch: search
  reqType: json
