spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: '{cipher}AQAD3jqPn9Bvb1nhJSLWmlLM5MOQDNyjnaXvbSOFfvqmomuN0MMuhyXyIqfxjShLnOFtwj3VL56OmRttYCTt2qXhK857hwxSthV3v4SbKsuI2YMFAIEVmeNBt6wFlfylcftu+f1MxA4EMcInLzwYPRX5DsSANfdfX1BuY++l1QGNf6UwMuEtiIbPqMJ8dmaQu3P+Ggt0VZfpobHicyZJUL9xxQ+7EtuyxRM9sB61Wp6J789Bw97TvSi8MFS2PEHjP18sDjcJjTO8GUO7zo3wZegP4Z/ZSSvM5qXpbg+dGdKHDRYpoiU8ow6prmdBPFUntTCqyvhDKpi+fnnVFS/wtIx/5Kzsa860cBOR1z++HpK9hcVP56i7aRETibbopgta8tg='
    password: 

token:
  expiration_time: 864000000
  secret: '{cipher}AQBBczoQeAW3ntSABMSl1ZW/ei/tqKkX8R/Lxk6CTZjlQuhPGB+bRt1sK7YRVphxufMQU32JgDMkvarkRXnrQVLZgTdNSjqbw5V5JMi/uADUy5ZHGC/Vqx2fIF7PvXi+WtAZNzLcOAf3ioiH1/tMaraEZIIpsf586WPCjrqjiIh0ajY1XdAiZxdQKcpDGqXvvYCLoVrfcezCSutDcwGjEVNHi6bRUhNFqmlTW2rhPR5/s4ZZ8LAcQl0qMWmI9FZkLSZIlqAoWzlszXgT5Bacmd6Ly06IiTOUsL3P3+i8SJAdDlKhOgSuIgaqAotlm4nFi2RrpH+wLQPLoGFjeUxyBDupTVDj0Pz5Oc6MUeb/5C0XdM0OGJ56QdXrSCcs0ZWxzBrlkZFUxnNu8RMCytKpi1tawBqWW8vn3UoMy2uQAjPiw2jmVIBUu3F7l8p12BGZ+Pw='

gateway:
  ip: 172.18.0.5
