spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: '{cipher}AQAD3jqPn9Bvb1nhJSLWmlLM5MOQDNyjnaXvbSOFfvqmomuN0MMuhyXyIqfxjShLnOFtwj3VL56OmRttYCTt2qXhK857hwxSthV3v4SbKsuI2YMFAIEVmeNBt6wFlfylcftu+f1MxA4EMcInLzwYPRX5DsSANfdfX1BuY++l1QGNf6UwMuEtiIbPqMJ8dmaQu3P+Ggt0VZfpobHicyZJUL9xxQ+7EtuyxRM9sB61Wp6J789Bw97TvSi8MFS2PEHjP18sDjcJjTO8GUO7zo3wZegP4Z/ZSSvM5qXpbg+dGdKHDRYpoiU8ow6prmdBPFUntTCqyvhDKpi+fnnVFS/wtIx/5Kzsa860cBOR1z++HpK9hcVP56i7aRETibbopgta8tg='
    password: 

token:
  expiration_time: 864000000
  secret: '{cipher}AQBBczoQeAW3ntSABMSl1ZW/ei/tqKkX8R/Lxk6CTZjlQuhPGB+bRt1sK7YRVphxufMQU32JgDMkvarkRXnrQVLZgTdNSjqbw5V5JMi/uADUy5ZHGC/Vqx2fIF7PvXi+WtAZNzLcOAf3ioiH1/tMaraEZIIpsf586WPCjrqjiIh0ajY1XdAiZxdQKcpDGqXvvYCLoVrfcezCSutDcwGjEVNHi6bRUhNFqmlTW2rhPR5/s4ZZ8LAcQl0qMWmI9FZkLSZIlqAoWzlszXgT5Bacmd6Ly06IiTOUsL3P3+i8SJAdDlKhOgSuIgaqAotlm4nFi2RrpH+wLQPLoGFjeUxyBDupTVDj0Pz5Oc6MUeb/5C0XdM0OGJ56QdXrSCcs0ZWxzBrlkZFUxnNu8RMCytKpi1tawBqWW8vn3UoMy2uQAjPiw2jmVIBUu3F7l8p12BGZ+Pw='

gateway:
  ip: 172.18.0.5

mail:
  username: '{cipher}AQDCxTV24iDeukZJ7FE8MS/jr0GuW/0YMUFiaMdJfwR3PzwEdXNgPOJAaL4NnpxHfpJCMNiLWXlNq4oamMK1nA5aJ69PHMa2LjNZlpGAQCJjI6ecfn5utDbXI3LG1PPPvYTwC3pxdWFNSrebrFakCzXFbnG9r9RxqNxM7Iibk3wAB5LQ0QvdocmvIn9hlv8rF5qRdFnGyUFvx7UDBUdWXPsoCPXF8EXPSZGuSEEkaX6nlrtY+neIxuCkZanLC7xRTR0bjLciiIlkeEv85nKc2VamTWLa1tmZU/LoFcXs848A27csDHcekDCRnYFjnWbmpJcgBv6iHwEZUY6qinUI5iLbzm7r+q0b3KGEZZEboG+LtKrJ69iKsngJPFmRS9XsKBs='
  password: '{cipher}AQB+CirUJ6eVL3p3icLYg0uV/NCpnPSkvQqDa5kwCm9noeo9WdrBsVzQCU5T7EYTbPCN1jIUvXvfcZDw3yhy1a2GsTTNYKkLcGAuZhpm0TYX++fJ8ZUexa+LktmKCYQCyRYXw+FpQjc0LHWWUXJihpUpoSVNCdWhxeb2zzNSVdaZJHiScztKM+w3FvJmOZlkWsyNJgx80HuVb8shPpLauTBZ5nFYnOHEV6FZq5dK/ovZQKe5onGjO1LFddOn5XQnvV8XvJHNHZPaD9BEeEVTzeb0aBHUV5Jv6CxTWnY/cNQGZCQe+zb0R5JhPfVSiei6YCrWM6AaNqG7fwuX+R7QS0CGhgRRPu9rjdwf6hubPzDCrgMfL/TkkZp9nAadw41Htye9X8LKizOd+3IxuMTSB9Q+'
